export const circuitData = [
  {
    id: 0,
    name: "Bahrain",
    flag: "https://dcoromina.s-ul.eu/f1/T8gEveZF",
    place: "Bahrain GP",
    image: "https://dcoromina.s-ul.eu/f1/tbtrG8e6",
  },
  {
    id: 1,
    name: "Saudi Arabia",
    flag: "https://dcoromina.s-ul.eu/f1/bUSaGOzF",
    place: "Saudi Arabian GP",
    image: "https://dcoromina.s-ul.eu/f1/WTNiaHJM",
  },
  {
    id: 2,
    name: "Australia",
    flag: "https://dcoromina.s-ul.eu/f1/NM1Xeay0",
    place: "Australian GP",
    image: "https://dcoromina.s-ul.eu/f1/WTNiaHJM",
  },
  {
    id: 3,
    name: "Japan",
    flag: "https://dcoromina.s-ul.eu/f1/NM1Xeay0",
    place: "Japanese GP",
    image: "https://dcoromina.s-ul.eu/f1/gKv8qgX7",
  },
  {
    id: 4,
    name: "China",
    flag: "https://dcoromina.s-ul.eu/f1/NM1Xeay0",
    place: "Chinese GP",
    image: "https://dcoromina.s-ul.eu/f1/gKv8qgX7",
  },
  {
    id: 5,
    name: "Miami",
    flag: "https://dcoromina.s-ul.eu/f1/NM1Xeay0",
    place: "Usa GP",
    image: "https://dcoromina.s-ul.eu/f1/gKv8qgX7",
  },
  {
    id: 6,
    name: "Emilia-Romagna",
    flag: "https://dcoromina.s-ul.eu/f1/NM1Xeay0",
    place: "Italian GP",
    image: "https://dcoromina.s-ul.eu/f1/gKv8qgX7",
  },
  {
    id: 7,
    name: "Monacp",
    flag: "https://dcoromina.s-ul.eu/f1/NM1Xeay0",
    place: "Canadian GP",
    image: "https://dcoromina.s-ul.eu/f1/gKv8qgX7",
  },
  {
    id: 8,
    name: "Canada",
    flag: "https://dcoromina.s-ul.eu/f1/NM1Xeay0",
    place: "Canada GP",
    image: "https://dcoromina.s-ul.eu/f1/gKv8qgX7",
  },
  {
    id: 9,
    name: "Barcelona",
    flag: "https://dcoromina.s-ul.eu/f1/NM1Xeay0",
    place: "Spaing GP",
    image: "https://dcoromina.s-ul.eu/f1/gKv8qgX7",
  },
  {
    id: 10,
    name: "Austria",
    flag: "https://dcoromina.s-ul.eu/f1/NM1Xeay0",
    place: "Austria GP",
    image: "https://dcoromina.s-ul.eu/f1/gKv8qgX7",
  },
  {
    id: 11,
    name: "Great Britain",
    flag: "https://dcoromina.s-ul.eu/f1/NM1Xeay0",
    place: "British GP",
    image: "https://dcoromina.s-ul.eu/f1/gKv8qgX7",
  },
  {
    id: 12,
    name: "Hungary",
    flag: "https://dcoromina.s-ul.eu/f1/NM1Xeay0",
    place: "Spaing GP",
    image: "https://dcoromina.s-ul.eu/f1/gKv8qgX7",
  },
  {
    id: 13,
    name: "Belgium",
    flag: "https://dcoromina.s-ul.eu/f1/NM1Xeay0",
    place: "German GP",
    image: "https://dcoromina.s-ul.eu/f1/gKv8qgX7",
  },
  {
    id: 14,
    name: "Netherlands",
    flag: "https://dcoromina.s-ul.eu/f1/NM1Xeay0",
    place: "Spaing GP",
    image: "https://dcoromina.s-ul.eu/f1/gKv8qgX7",
  },
  {
    id: 15,
    name: "Azerbaijan",
    flag: "https://dcoromina.s-ul.eu/f1/NM1Xeay0",
    place: "Spaing GP",
    image: "https://dcoromina.s-ul.eu/f1/gKv8qgX7",
  },
  {
    id: 16,
    name: "Singapore",
    flag: "https://dcoromina.s-ul.eu/f1/NM1Xeay0",
    place: "Spaing GP",
    image: "https://dcoromina.s-ul.eu/f1/gKv8qgX7",
  },
  {
    id: 17,
    name: "Vegas",
    flag: "https://dcoromina.s-ul.eu/f1/NM1Xeay0",
    place: "Usa GP",
    image: "https://dcoromina.s-ul.eu/f1/gKv8qgX7",
  },
  {
    id: 18,
    name: "Mexico",
    flag: "https://dcoromina.s-ul.eu/f1/NM1Xeay0",
    place: "Mexico city GP",
    image: "https://dcoromina.s-ul.eu/f1/gKv8qgX7",
  },
  {
    id: 19,
    name: "Sao Paulo",
    flag: "https://dcoromina.s-ul.eu/f1/NM1Xeay0",
    place: "Brazil GP",
    image: "https://dcoromina.s-ul.eu/f1/gKv8qgX7",
  },
  {
    id: 20,
    name: "Barcelona",
    flag: "https://dcoromina.s-ul.eu/f1/NM1Xeay0",
    place: "Spaing GP",
    image: "https://dcoromina.s-ul.eu/f1/gKv8qgX7",
  },
  {
    id: 21,
    name: "Barcelona",
    flag: "https://dcoromina.s-ul.eu/f1/NM1Xeay0",
    place: "Spaing GP",
    image: "https://dcoromina.s-ul.eu/f1/gKv8qgX7",
  },
  {
    id: 22,
    name: "Barcelona",
    flag: "https://dcoromina.s-ul.eu/f1/NM1Xeay0",
    place: "Spaing GP",
    image: "https://dcoromina.s-ul.eu/f1/gKv8qgX7",
  },
];
